/* SPDX-License-Identifier: BSD-2-Clause */

/**
 * @file
 *
 * @ingroup RTEMSBSPsRISCVMBV
 *
 * @brief Clock driver for the AMD MicroBlaze V generic BSP.
 *
 * The platform has no CLINT, so there is no mtime/mtimecmp device and the
 * RISC-V time CSR does not advance.  The clock tick is generated by channel 0
 * of the Xilinx AXI Timer, which interrupts through input MBV_TIMER_IRQ of
 * the AXI Interrupt Controller.  Channel 1 of the same timer runs freely and
 * provides the timecounter and the CPU counter.
 */

/*
 * Copyright (C) 2026 Samuel Price
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <bsp.h>
#include <bsp/fatal.h>
#include <bsp/irq.h>
#include <bsp/mbv.h>

#include <rtems.h>
#include <rtems/sysinit.h>
#include <rtems/timecounter.h>

static struct timecounter mbv_clock_tc;

/* Counter increments of channel 1 per clock tick */
static uint32_t mbv_clock_interval;

/* Expected channel 1 counter value at the next clock tick */
static uint32_t mbv_clock_next_ref;

static uint32_t mbv_clock_get_timecount(struct timecounter *tc)
{
  (void) tc;

  return MBV_TIMER->tcr1;
}

uint32_t _CPU_Counter_frequency(void)
{
  return MBV_TIMER_FREQUENCY;
}

CPU_Counter_ticks _CPU_Counter_read(void)
{
  return (CPU_Counter_ticks) MBV_TIMER->tcr1;
}

static void mbv_counter_initialize(void)
{
  volatile Microblaze_Timer *timer = MBV_TIMER;

  /*
   * Channel 1: free-running up counter used by the CPU counter and the
   * timecounter.  With a load value of zero and auto reload, the counter
   * wraps through the full 32-bit range.  No interrupt is generated.
   *
   * This runs from a system initialization item so that the CPU counter
   * works in applications which do not need the clock driver.
   */
  timer->tcsr1 = MICROBLAZE_TIMER_TCSR0_T0INT;
  timer->tlr1 = 0;
  timer->tcsr1 = MICROBLAZE_TIMER_TCSR0_LOAD0;
  timer->tcsr1 = MICROBLAZE_TIMER_TCSR0_ARHT0 | MICROBLAZE_TIMER_TCSR0_ENT0;
}

RTEMS_SYSINIT_ITEM(
  mbv_counter_initialize,
  RTEMS_SYSINIT_CPU_COUNTER,
  RTEMS_SYSINIT_ORDER_FIRST
);

static void mbv_clock_initialize(void)
{
  uint64_t us_per_tick = rtems_configuration_get_microseconds_per_tick();
  uint32_t counter_ticks_per_clock_tick =
    (uint32_t) ((MBV_TIMER_FREQUENCY * us_per_tick) / 1000000);
  volatile Microblaze_Timer *timer = MBV_TIMER;

  /*
   * Channel 0: clock tick generator.  Down counter, auto reload, interrupt
   * enabled.  The interrupt line is input MBV_TIMER_IRQ of the AXI Interrupt
   * Controller (level-sensitive).
   */

  /* Stop the timer, clear a pending interrupt */
  timer->tcsr0 = MICROBLAZE_TIMER_TCSR0_T0INT;

  /* Set the tick period and load it into the counter */
  timer->tlr0 = counter_ticks_per_clock_tick - 1;
  timer->tcsr0 = MICROBLAZE_TIMER_TCSR0_LOAD0;

  /* Phase reference for the tick period trimming in mbv_clock_at_tick() */
  mbv_clock_interval = counter_ticks_per_clock_tick;
  mbv_clock_next_ref = timer->tcr1 + counter_ticks_per_clock_tick;

  /* Enable: auto reload, interrupt, down counter, start */
  timer->tcsr0 = MICROBLAZE_TIMER_TCSR0_ARHT0 | MICROBLAZE_TIMER_TCSR0_ENIT0 |
    MICROBLAZE_TIMER_TCSR0_UDT0 | MICROBLAZE_TIMER_TCSR0_ENT0;

  /* Install timecounter */
  mbv_clock_tc.tc_get_timecount = mbv_clock_get_timecount;
  mbv_clock_tc.tc_counter_mask = 0xffffffff;
  mbv_clock_tc.tc_frequency = MBV_TIMER_FREQUENCY;
  mbv_clock_tc.tc_quality = RTEMS_TIMECOUNTER_QUALITY_CLOCK_DRIVER;
  rtems_timecounter_install(&mbv_clock_tc);
}

static void mbv_clock_at_tick(void)
{
  volatile Microblaze_Timer *timer = MBV_TIMER;

  if ((timer->tcsr0 & MICROBLAZE_TIMER_TCSR0_T0INT) != 0) {
    uint32_t interval = mbv_clock_interval;
    uint32_t now = timer->tcr1;
    int32_t error;
    uint32_t period;

    /*
     * Trim the next tick period by the measured phase error against the
     * free-running channel 1.  On real hardware the error is a few counter
     * increments (interrupt latency), so this is practically a no-op.  On
     * emulators which re-arm the timer from the interrupt callback (for
     * example the QEMU xlnx.xps-timer model), each period would otherwise be
     * stretched by the callback latency and tick-based time would drift
     * significantly against the timecounter.
     */
    error = (int32_t) (now - mbv_clock_next_ref);

    if (error > (int32_t) (4 * interval)) {
      /* Too far behind (emulator stall): drop the lost time and resync */
      mbv_clock_next_ref = now + interval;
      period = interval;
    } else {
      int32_t limit = (int32_t) (interval / 2);

      if (error > limit) {
        error = limit;
      } else if (error < -limit) {
        error = -limit;
      }

      period = (uint32_t) ((int32_t) interval - error);
      mbv_clock_next_ref += interval;
    }

    /*
     * Set the length of the next period.  With auto reload, the new load
     * value takes effect at the next reload on real hardware and immediately
     * in QEMU (the interrupt acknowledge write below re-arms the timer).
     */
    timer->tlr0 = period - 1;

    /* Clear the interrupt at the timer */
    timer->tcsr0 |= MICROBLAZE_TIMER_TCSR0_T0INT;
  }
}

static void mbv_clock_handler_install(rtems_interrupt_handler isr)
{
  rtems_status_code sc;

  sc = rtems_interrupt_handler_install(
    MBV_INTERRUPT_VECTOR_EXTERNAL(MBV_TIMER_IRQ),
    "Clock",
    RTEMS_INTERRUPT_UNIQUE,
    isr,
    NULL
  );
  if (sc != RTEMS_SUCCESSFUL) {
    bsp_fatal(RISCV_FATAL_CLOCK_IRQ_INSTALL);
  }
}

#define Clock_driver_support_at_tick(arg) mbv_clock_at_tick()

#define Clock_driver_support_initialize_hardware() mbv_clock_initialize()

#define Clock_driver_support_install_isr(isr) mbv_clock_handler_install(isr)

#include "../../../shared/dev/clock/clockimpl.h"
